### ISSUE TITLE
Amazon folder questions indentation is not good.(Its difficult to find where questions getting start or end).

### ISSUE THREAD

**Issue by mandepsingh** [achoudh5/Hacktoberfest_Interview_Questions_2020#21]

**Comment by achoudh5** [comment]
@mandepsingh would you like to work on this issue? I see it was initially added by you, if you can work on it that'll be great :)

**Comment by mandepsingh** [comment]
yes, Of course

**Comment by achoudh5** [comment]
Please raise a PR for the same @mandepsingh
